# BCM Application Makefile
PROJECTNAME = bcm_app

include $(ROOTDIR)/scripts/project_defaults.mk

# Override linker script with absolute path
override ldcmdfile-y = $(ROOTDIR)/boards/stm32f103_bcm/linkscript_gcc.lcf
